
import javax.swing.JOptionPane;

public class AgentDashboard extends javax.swing.JFrame {

	private String username = "";

	public AgentDashboard() {
		initComponents();
	}

	public AgentDashboard(String tempUserName) {
		initComponents();
		setLocationRelativeTo(null);
		username = tempUserName;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plotsButton = new javax.swing.JButton();
        homesButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaasthu Nirmaan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agent Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        plotsButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        plotsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plot.png"))); // NOI18N
        plotsButton.setText("Plots");
        plotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(plotsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 290, -1));

        homesButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        homesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homesButton.setText("Homes");
        homesButton.setMaximumSize(new java.awt.Dimension(227, 71));
        homesButton.setMinimumSize(new java.awt.Dimension(227, 71));
        homesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        signoutButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        signoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        signoutButton.setText("Sign Out");
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 360, -1));

        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_one.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotsButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new BuyPlots(username).setVisible(true);
    }//GEN-LAST:event_plotsButtonActionPerformed

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
		// TODO add your handling code here:
		int logout = JOptionPane.showConfirmDialog(null, "Do you really want to exit", "Really", JOptionPane.YES_NO_OPTION);
		if (logout == 0) {
			setVisible(false);
			new Login().setVisible(true);
		}
    }//GEN-LAST:event_signoutButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new AgentProfile(username).setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void homesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homesButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new BuyHome(username).setVisible(true);
    }//GEN-LAST:event_homesButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AgentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AgentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AgentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AgentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AgentDashboard().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton plotsButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton signoutButton;
    // End of variables declaration//GEN-END:variables
}
