
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sujith
 */
public class BuyPlots extends javax.swing.JFrame {

	/**
	 * Creates new form ShowHome
	 */
	String username = "";

	public BuyPlots() {
		initComponents();
	}

	public BuyPlots(String tempUsername) {
		initComponents();
		setLocationRelativeTo(null);
		username = tempUsername;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaasthu Nirmaan");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 24, 184));
        jLabel1.setText("Plots");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 6, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seller Name", "Seller Id", "Agent Name", "Colony Name", "City Name", "State", "Price", "Facing", "Square Feet", "Date Of Registration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 1280, -1));

        backButton.setBackground(new java.awt.Color(176, 244, 180));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_two.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new AgentDashboard(username).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		// TODO add your handling code here:
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		try {
			Connection con = ConnectionProvider.getCon();
			Statement s = con.createStatement();
			ResultSet rs = s.executeQuery("select * from plot, customer, agent where sellerID = customer.aadharID and agentID = agent.aadharID and agent.area = plot.cityName and endDate is NULL and agentID = '" + username + "'");
			while (rs.next()) {
				model.addRow(new Object[]{rs.getString("customer.firstName"), rs.getString("plot.sellerID"), rs.getString("agent.firstName"), rs.getString("plot.colonyName"), rs.getString("plot.cityName"), rs.getString("plot.state"), rs.getString("plot.price"), rs.getString("plot.facing"), rs.getString("plot.squareFeet"), rs.getString("plot.startDate")});
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
		// TODO add your handling code here:
		JTable table = (JTable) evt.getSource();
		int row = table.getSelectedRow(); // Get the selected row index

		// Get the values from the selected row in the JTable
		String sellerId = (String) table.getValueAt(row, 1);
		String dateOfRegistration = (String) table.getValueAt(row, 9);

		// Prompt user to enter new BuyerID and new EndDate using JOptionPane
		String newBuyerID = JOptionPane.showInputDialog("Enter new BuyerID:");
		String newEndDate = JOptionPane.showInputDialog("Enter new EndDate (yyyy-MM-dd):");

		// Update the database with the new values
		if (newBuyerID == null && newEndDate == null) {
			try {
				Connection con = ConnectionProvider.getCon(); // Get database connection
				String query = "UPDATE plot SET BuyerID = ?, EndDate = ? WHERE SellerID = ? and AgentID = '" + username + "'" + " and startDate = '" + dateOfRegistration + "'"; // Update query
				PreparedStatement stmt = con.prepareStatement(query);
				stmt.setString(1, newBuyerID);
				stmt.setString(2, newEndDate);
				stmt.setString(3, sellerId);
				int result = stmt.executeUpdate(); // Execute the update query

				if (result > 0) {
					JOptionPane.showMessageDialog(null, "Values updated successfully!"); // Show success message
				} else {
					JOptionPane.showMessageDialog(null, "Failed to update values."); // Show error message
				}

				// Close database resources
				stmt.close();
				con.close();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else {
			JOptionPane.showMessageDialog(null, "Plot already bought. ");
		}
    }//GEN-LAST:event_jTable1MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShowHome().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
