
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sujith
 */
public class CustomerDashboard extends javax.swing.JFrame {

	/**
	 * Creates new form CustomerDashboard
	 */
	public String username = "";

	public CustomerDashboard() {
		initComponents();
	}

	public CustomerDashboard(String tempUsername) {
		initComponents();
		setLocationRelativeTo(null);
		username = tempUsername;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateProfileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buyPlotButton = new javax.swing.JButton();
        buyHomeButton = new javax.swing.JButton();
        saleHomeButton = new javax.swing.JButton();
        salePlotButton = new javax.swing.JButton();
        signoutButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaasthu Nirmaan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateProfileButton.setText("Update Profile");
        updateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 138, 138));
        jLabel1.setText("Vaasthu Nirmaan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 148, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 115, 97));
        jLabel3.setText("Real Estate Redefined: Homes and Plots for Your Future!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 218, -1, -1));

        buyPlotButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buyPlotButton.setText("Buy Plot");
        buyPlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPlotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyPlotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 140, -1));

        buyHomeButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buyHomeButton.setText("Buy Home");
        buyHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        saleHomeButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        saleHomeButton.setText("Sell Home");
        saleHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saleHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        salePlotButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salePlotButton.setText("Sell Plot");
        salePlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salePlotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salePlotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 140, -1));

        signoutButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signoutButton.setText("Sign out");
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_one.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salePlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salePlotButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new SalePlot(username).setVisible(true);
    }//GEN-LAST:event_salePlotButtonActionPerformed

    private void saleHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleHomeButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new SaleHome(username).setVisible(true);
    }//GEN-LAST:event_saleHomeButtonActionPerformed

    private void buyPlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPlotButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new ShowPlots(username).setVisible(true);
    }//GEN-LAST:event_buyPlotButtonActionPerformed

    private void buyHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyHomeButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new ShowHome(username).setVisible(true);
    }//GEN-LAST:event_buyHomeButtonActionPerformed

    private void updateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new CustomerProfile(username).setVisible(true);
    }//GEN-LAST:event_updateProfileButtonActionPerformed

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
		// TODO add your handling code here:
		int logout = JOptionPane.showConfirmDialog(null, "Do you really want to exit", "Really", JOptionPane.YES_NO_OPTION);
		if (logout == 0) {
			setVisible(false);
			new Login().setVisible(true);
		}
    }//GEN-LAST:event_signoutButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CustomerDashboard().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyHomeButton;
    private javax.swing.JButton buyPlotButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton saleHomeButton;
    private javax.swing.JButton salePlotButton;
    private javax.swing.JButton signoutButton;
    private javax.swing.JButton updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
