
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import dao.ConnectionProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sujith
 */
public class Register extends javax.swing.JFrame {

	/**
	 * Creates new form Register
	 */
	public Register() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        selectRole = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaasthu Nirmaan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 24, 184));
        jLabel1.setText("Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 24, 184));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 263, 300, -1));
        getContentPane().add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 329, 300, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(104, 24, 184));
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 381, 300, -1));
        getContentPane().add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 447, 300, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(104, 24, 184));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 505, 300, -1));
        getContentPane().add(txtMNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 571, 300, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 24, 184));
        jLabel5.setText("Aadhar Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 263, 300, -1));

        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 329, 300, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(104, 24, 184));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 381, 300, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(104, 24, 184));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 505, 300, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 571, 300, 40));

        selectRole.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agent", "Customer" }));
        getContentPane().add(selectRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 183, -1, -1));

        saveButton.setBackground(new java.awt.Color(171, 245, 177));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(163, 17, 207));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 654, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 300, 40));

        backButton.setBackground(new java.awt.Color(176, 244, 180));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_two.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
		// TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		// TODO add your handling code here:
		String userRole = (String) selectRole.getSelectedItem();
		String fName = txtFName.getText();
		String lName = txtLName.getText();
		String mNumber = txtMNumber.getText();
		String aadhar = txtUserName.getText();
		String password = new String(txtPassword.getPassword());
		String address = txtAddress.getText();
		String mobileNumberPattern = "[6789]\\d{9}";
		String aadharNumberPattern = "\\d{12}";

		if (fName.equals("")) {
			JOptionPane.showMessageDialog(null, "First Name field required");
		} else if (lName.equals("")) {
			JOptionPane.showMessageDialog(null, "Last Name field Required. ");
		} else if (mNumber.equals("")) {
			JOptionPane.showMessageDialog(null, "Mobile Number field Required. ");
		} else if (aadhar.equals("")) {
			JOptionPane.showMessageDialog(null, "Aadhar field Required. ");
		} else if (password.equals("")) {
			JOptionPane.showMessageDialog(null, "Password field Required. ");
		} else if (!mNumber.matches(mobileNumberPattern) || mNumber.length() != 10) {
			JOptionPane.showMessageDialog(null, "Mobile number invalid. ");
		} else if (!aadhar.matches(aadharNumberPattern)) {
			JOptionPane.showMessageDialog(null, "Aadhar number invalid. ");
		} else if (userRole.equals("Agent") && address.equals("")) {
			JOptionPane.showMessageDialog(null, "Address field Required");
		} else {
			try {
				JOptionPane.showMessageDialog(null, "Username is A followed by your aadhar number.");
				Connection con = ConnectionProvider.getCon();
				PreparedStatement ps;
				if (userRole.equals("Agent")) {
					aadhar = 'A' + aadhar;
					ps = con.prepareStatement("insert into agent (firstName, lastName, aadharID, phoneNumber, Area, password) values(?,?,?,?,?,?)");
					ps.setString(1, fName);
					ps.setString(2, lName);
					ps.setString(3, aadhar);
					ps.setString(4, mNumber);
					ps.setString(5, address);
					ps.setString(6, password);
					ps.executeUpdate();
					JOptionPane.showMessageDialog(null, "Succesfully created", "Success", JOptionPane.YES_NO_OPTION);
					setVisible(false);
					new Register().setVisible(true);
				} else {
					aadhar = 'C' + aadhar;
					JOptionPane.showMessageDialog(null, "Username is A followed by your aadhar number.");
					String q = "insert into customer (firstName, lastName, aadharID, phoneNumber, password)values(?,?,?,?,?)";
					ps = con.prepareStatement(q);
					ps.setString(1, fName);
					ps.setString(2, lName);
					ps.setString(3, aadhar);
					ps.setString(4, mNumber);
					ps.setString(5, password);
					ps.executeUpdate();
					JOptionPane.showMessageDialog(null, "Succesfully created", "Success", JOptionPane.YES_NO_OPTION);
					setVisible(false);
					new Register().setVisible(true);
				}
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e, "Connection error", JOptionPane.YES_NO_OPTION);
				System.out.println(e);
			}
		}
    }//GEN-LAST:event_saveButtonActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
		// TODO add your handling code here:

    }//GEN-LAST:event_txtAddressActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new Login().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Register().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> selectRole;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
