
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sujith
 */
public class ShowHome extends javax.swing.JFrame {

	/**
	 * Creates new form ShowHome
	 */
	String username = "";
	DefaultTableModel model = null;

	public ShowHome() {
		initComponents();
	}

	public ShowHome(String tempUsername) {
		initComponents();
		setLocationRelativeTo(null);
		username = tempUsername;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBHK = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtSS = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtColony = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPriceMin = new javax.swing.JTextField();
        txtPriceMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFacing = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtYOC = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtSquareFeetMin = new javax.swing.JTextField();
        txtSquareFeetMax = new javax.swing.JTextField();
        Find = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaasthu Nirmaan");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 24, 184));
        jLabel1.setText("Homes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 6, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seller Name", "Agent Name", "Selling State", "Colony Name", "City Name", "State", "Price", "Facing", "Year Of Construction", "Square Feet", "BHK", "Agent ID", "SellerID", "Start Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTable1HierarchyChanged(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 72, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 24, 184));
        jLabel2.setText("BHK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 108, -1));
        getContentPane().add(txtBHK, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 97, 100, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(104, 24, 184));
        jLabel3.setText("Selling State");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, -1, -1));

        txtSS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rent", "Sale", " " }));
        getContentPane().add(txtSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 140, 100, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(104, 24, 184));
        jLabel4.setText("Colony ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 108, -1));
        getContentPane().add(txtColony, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 184, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 24, 184));
        jLabel5.setText("City");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, 108, -1));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 224, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(104, 24, 184));
        jLabel6.setText("State");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 108, -1));
        getContentPane().add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 267, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(104, 24, 184));
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, 108, -1));
        getContentPane().add(txtPriceMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 353, 108, -1));
        getContentPane().add(txtPriceMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 353, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(104, 24, 184));
        jLabel8.setText("Facing");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 393, 108, -1));

        txtFacing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North", "South", "East", "West", " " }));
        getContentPane().add(txtFacing, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 393, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(104, 24, 184));
        jLabel9.setText("YOC");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 436, 108, -1));

        txtYOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", " " }));
        getContentPane().add(txtYOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 440, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(104, 24, 184));
        jLabel10.setText("Square Feet");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 480, 108, -1));
        getContentPane().add(txtSquareFeetMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 523, 108, -1));
        getContentPane().add(txtSquareFeetMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 523, 100, -1));

        Find.setBackground(new java.awt.Color(176, 244, 180));
        Find.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Find.setForeground(new java.awt.Color(163, 17, 207));
        Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applyFilters.png"))); // NOI18N
        Find.setText("Find");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        getContentPane().add(Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 634, -1, -1));

        backButton.setBackground(new java.awt.Color(176, 244, 180));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_two.png"))); // NOI18N
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		new CustomerDashboard(username).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		// TODO add your handling code here:

		try {
			model = (DefaultTableModel) jTable1.getModel();
			Connection con = ConnectionProvider.getCon();
			Statement s = con.createStatement();
			ResultSet rs = s.executeQuery("select * from home, customer, agent where sellerID = customer.aadharID and agentID = agent.aadharID and agent.area = home.cityName and home.endDate is NULL");
			while (rs.next()) {
				model.addRow(new Object[]{rs.getString("customer.firstName"), rs.getString("agent.firstName"), rs.getString("home.sellingState"), rs.getString("home.colonyName"), rs.getString("home.cityName"), rs.getString("home.state"), rs.getString("home.price"), rs.getString("home.facing"), rs.getString("home.yearOfConstruction"), rs.getString("home.squareFeet"), rs.getString("home.bhk"), rs.getString("agent.aadharID"), rs.getString("home.sellerID"), rs.getString("home.startDate")});
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}

    }//GEN-LAST:event_formComponentShown

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
		// TODO add your handling code here:
		String colony = txtColony.getText();
		String city = txtCity.getText();
		String priceMin = txtPriceMin.getText();
		String priceMax = txtPriceMax.getText();
		String facing = (String) txtFacing.getSelectedItem();
		String sqftMin = txtSquareFeetMax.getText();
		String sqftMax = txtSquareFeetMax.getText();
		String ss = (String) txtSS.getSelectedItem();
		String yoc = (String) txtYOC.getSelectedItem();
		Integer bed = (Integer) txtBHK.getValue();
		String bhk = Integer.toString(bed);
		try {
			Connection con = ConnectionProvider.getCon();
			if (colony.equals("")) {
				colony = "colonyName != '0' and ";
			} else {
				colony = "colonyName = '" + colony + "' and ";
			}
			if (city.equals("")) {
				city = "cityName != '0' and ";
			} else {
				city = "cityName = '" + city + "' and ";
			}
			if (priceMin.equals("")) {
				priceMin = "price between " + "'0'" + " and ";
			} else {
				priceMin = "price between '" + priceMin + "' and ";
			}
			if (priceMax.equals("")) {
				priceMax = "'100000000'" + "and ";
			} else {
				priceMax = "'" + priceMax + "' and ";
			}
			if (facing.equals(" ")) {
				facing = "facing != '0' and ";
			} else {
				facing = "facing = '" + facing + "' and ";
			}
			if (bhk.equals("0")) {
				bhk = "bhk > '0' and ";
			} else {
				bhk = "bhk = '" + bhk + "' and ";
			}
			if (ss.equals(" ")) {
				ss = "sellingState != '0' and ";
			} else {
				ss = "sellingState = '" + ss + "' and ";
			}
			if (yoc.equals(" ")) {
				yoc = "yearOfConstruction != '0' and ";
			} else {
				yoc = "yearOfConstruction = '" + yoc + "' and ";
			}
			if (sqftMin.equals("")) {
				sqftMin = "squareFeet between " + "'0'" + " and ";
			} else {
				sqftMin = "squareFeet between '" + sqftMin + "' and ";
			}
			if (sqftMax.equals("")) {
				sqftMax = "'10000000'";
			} else {
				sqftMax = "'" + sqftMax + "'";
			}
			model = (DefaultTableModel) jTable1.getModel();
			model.setRowCount(0);
			String query = "SELECT * FROM home, customer, agent where " + colony + city + priceMin + priceMax + facing + bhk + yoc + ss + sqftMin + sqftMax + " and agent.aadharID = home.agentID and customer.aadharID = home.sellerID and agent.area = home.cityName and home.endDate is NULL";
			Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery(query);
			System.out.println("RS done successfully");
			while (rs.next()) {
				model.addRow(new Object[]{rs.getString("customer.firstName"), rs.getString("agent.firstName"), rs.getString("home.sellingState"), rs.getString("home.colonyName"), rs.getString("home.cityName"), rs.getString("home.state"), rs.getString("home.price"), rs.getString("home.facing"), rs.getString("home.yearOfConstruction"), rs.getString("home.squareFeet"), rs.getString("home.bhk"), rs.getString("agent.aadharID"), rs.getString("home.sellerID"), rs.getString("home.startDate")});
				System.out.println("Row added");
			}
			con.close();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}
    }//GEN-LAST:event_FindActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
		// TODO add your handling code here:
		try {
			Connection con = ConnectionProvider.getCon();
			int index = jTable1.getSelectedRow();
			@SuppressWarnings("LocalVariableHidesMemberVariable")
			TableModel model = jTable1.getModel();
			int col = 11;
			String id = model.getValueAt(index, col).toString();
			System.out.println("Value: " + id);
			Statement s = con.createStatement();
			String number;
			ResultSet rs = s.executeQuery("select * from agent where aadharID = '" + id + "'");
			if (rs.next()) {
				number = rs.getString(4);
			} else {
				number = "";
			}
			JOptionPane.showMessageDialog(null, "Phone Number: " + number);
			System.out.println(id);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
			System.out.println(e);
		}
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable1HierarchyChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_jTable1HierarchyChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ShowHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShowHome().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Find;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner txtBHK;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtColony;
    private javax.swing.JComboBox<String> txtFacing;
    private javax.swing.JTextField txtPriceMax;
    private javax.swing.JTextField txtPriceMin;
    private javax.swing.JComboBox<String> txtSS;
    private javax.swing.JTextField txtSquareFeetMax;
    private javax.swing.JTextField txtSquareFeetMin;
    private javax.swing.JTextField txtState;
    private javax.swing.JComboBox<String> txtYOC;
    // End of variables declaration//GEN-END:variables
}
